name: Docker Image CI

on:
  push:
    branches:
    - 'master'
    
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to registry
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login nikitatr991.fvds.ru -u $DOCKER_USER -p $DOCKER_PASSWORD

    -
      name: Install jdk
      run: |
        sudo apt update
        sudo apt install openjdk-17-jdk

    -
      name: Build configuration-service
      run: |
        cd configuration-service
        mvn package -DskipTests
        cd ..
        docker build ./cloud-discovery -t nikitatr/myvspc-cloud-discovery-docker:latest

    -
      name: Build cloud-discovery
      run: |
        cd cloud-discovery
        mvn package -DskipTests
        cd ..
        docker build ./cloud-discovery -t nikitatr/myvspc-cloud-discovery-docker:latest

    -
      name: Build api-gateway
      run: |
        cd api-gateway
        mvn package -DskipTests
        cd ..
        docker build ./api-gateway -t nikitatr/myvspc-api-gateway-docker:latest

    -
      name: Build news-service
      run: |
        cd news-service
        mvn package -DskipTests
        cd ..
        docker build ./news-service -t nikitatr/myvspc-news-service-docker:latest

    -
      name: Build schedule-service
      run: |
        cd schedule-service
        mvn package -DskipTests
        cd ..
        docker build ./schedule-service -t nikitatr/myvspc-schedule-service-docker:latest

    - name: docker push
      run: |
        docker push nikitatr/myvspc-configuration-service-docker:latest
        docker push nikitatr/myvspc-cloud-discovery-docker:latest
        docker push nikitatr/myvspc-api-gateway-docker:latest
        docker push nikitatr/myvspc-news-service-docker:latest
        docker push nikitatr/myvspc-schedule-service-docker:latest
