name: Docker Image CI

on:
  push:
    branches:
    - 'master'
    
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to registry
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login nikitatr991.fvds.ru -u $DOCKER_USER -p $DOCKER_PASSWORD

    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    -
      name: Build configuration-service
      run: |
        cd configuration-service
        mvn package -DskipTests
        docker build . -t nikitatr991.fvds.ru/myvspc-configuration-service-docker:latest

    -
      name: Build cloud-discovery
      run: |
        cd cloud-discovery
        mvn package -DskipTests
        docker build . -t nikitatr991.fvds.ru/myvspc-cloud-discovery-docker:latest

    -
      name: Build api-gateway
      run: |
        cd api-gateway
        mvn package -DskipTests
        docker build . -t nikitatr991.fvds.ru/myvspc-api-gateway-docker:latest

    -
      name: Build news-service
      run: |
        cd news-service
        mvn package -DskipTests
        docker build . -t nikitatr991.fvds.ru/myvspc-news-service-docker:latest

    -
      name: Build schedule-service
      run: |
        cd schedule-service
        mvn package -DskipTests
        docker build . -t nikitatr991.fvds.ru/myvspc-schedule-service-docker:latest

    - name: docker push
      run: |
        docker push nikitatr991.fvds.ru/myvspc-configuration-service-docker:latest
        docker push nikitatr991.fvds.ru/myvspc-cloud-discovery-docker:latest
        docker push nikitatr991.fvds.ru/myvspc-api-gateway-docker:latest
        docker push nikitatr991.fvds.ru/myvspc-news-service-docker:latest
        docker push nikitatr991.fvds.ru/myvspc-schedule-service-docker:latest
