name: Docker Image CI

on:
  push:
    branches:
    - 'master'
    
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - 
      name: Login to Rregistry
      uses: docker/login-action@v1
      with:
        registry: nikitatr991.fvds.ru
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker-compose build
    - 
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: name/app
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest
